export const NavigationRouts = {
  SPLASH: 'SPLASH',
  TABS: 'TABS',
  PRACTICE: 'PRACTICE',
  SUMMARY: 'SUMMARY',
	MANAGEMENT_STACK: 'MANAGEMENT_STACK',
  MANAGEMENT: 'MANAGEMENT',
	WORKOUT_CRUD: 'WORKOUT_CRUD',
  SETTINGS: 'SETTINGS',
};
